<a href="https://colab.research.google.com/github/Rijinputhiyonnan/ICT-daily-task-Rijin/blob/main/Data_Acquisition_Case_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [4]:
death_rate = pd.read_csv("/content/Death_rates_for_suicide__by_sex__race__Hispanic_origin__and_age__United_States.csv")

In [5]:
death_rate.head(10)

,INDICATOR,UNIT,UNIT_NUM,STUB_NAME,STUB_NAME_NUM,STUB_LABEL,STUB_LABEL_NUM,YEAR,YEAR_NUM,AGE,AGE_NUM,ESTIMATE,FLAG
0,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1950,1,All ages,0.0,13.2,NaN
1,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1960,2,All ages,0.0,12.5,NaN
2,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1970,3,All ages,0.0,13.1,NaN
3,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1980,4,All ages,0.0,12.2,NaN
4,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1981,5,All ages,0.0,12.3,NaN
5,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1982,6,All ages,0.0,12.5,NaN
6,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1983,7,All ages,0.0,12.4,NaN
7,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1984,8,All ages,0.0,12.6,NaN
8,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1985,9,All ages,0.0,12.5,NaN
9,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1986,10,All ages,0.0,13.0,NaN

In [6]:
death_rate.describe()

,UNIT_NUM,STUB_NAME_NUM,STUB_LABEL_NUM,YEAR,YEAR_NUM,AGE_NUM,ESTIMATE
count,6390.000000,6390.000000,6390.000000,6390.000000,6390.000000,6390.000000,5484.000000
mean,1.872926,4.621909,4.686775,1997.525822,22.692019,2.712207,13.709810
std,0.333081,2.031777,1.829624,14.937451,12.286033,1.932280,11.531805
min,1.000000,0.000000,0.000000,1950.000000,1.000000,0.000000,0.300000
25%,2.000000,3.000000,3.230000,1988.000000,12.000000,0.000000,5.000000
50%,2.000000,5.000000,5.125100,1999.000000,23.000000,3.000000,10.500000
75%,2.000000,6.000000,6.153000,2009.000000,33.000000,4.100000,19.500000
max,2.000000,11.000000,7.235000,2018.000000,42.000000,6.000000,74.800000

In [8]:
death_rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6390 entries, 0 to 6389
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   INDICATOR       6390 non-null   object
 1   UNIT            6390 non-null   object
 2   UNIT_NUM        6390 non-null   int64
 3   STUB_NAME       6390 non-null   object
 4   STUB_NAME_NUM   6390 non-null   int64
 5   STUB_LABEL      6390 non-null   object
 6   STUB_LABEL_NUM  6390 non-null   float64
 7   YEAR            6390 non-null   int64
 8   YEAR_NUM        6390 non-null   int64
 9   AGE             6390 non-null   object
 10  AGE_NUM         6390 non-null   float64
 11  ESTIMATE        5484 non-null   float64
 12  FLAG            906 non-null    object
dtypes: float64(3), int64(4), object(6)
memory usage: 649.1+ KB

In [10]:
death_rate.shape

(6390, 13)

In [11]:
death_rate.isnull()

,INDICATOR,UNIT,UNIT_NUM,STUB_NAME,STUB_NAME_NUM,STUB_LABEL,STUB_LABEL_NUM,YEAR,YEAR_NUM,AGE,AGE_NUM,ESTIMATE,FLAG
0,False,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6385,False,False,False,False,False,False,False,False,False,False,False,False,True
6386,False,False,False,False,False,False,False,False,False,False,False,False,True
6387,False,False,False,False,False,False,False,False,False,False,False,False,True
6388,False,False,False,False,False,False,False,False,False,False,False,False,True
6389,False,False,False,False,False,False,False,False,False,False,False,False,True

In [12]:
death_rate.isnull().sum()

INDICATOR            0
UNIT                 0
UNIT_NUM             0
STUB_NAME            0
STUB_NAME_NUM        0
STUB_LABEL           0
STUB_LABEL_NUM       0
YEAR                 0
YEAR_NUM             0
AGE                  0
AGE_NUM              0
ESTIMATE           906
FLAG              5484
dtype: int64

In [15]:
death_rate["YEAR"].unique()

array([1950, 1960, 1970, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018])

In [17]:
death_rate["YEAR"].nunique()

42

In [18]:
death_rate['ESTIMATE'].describe()

count    5484.000000
mean       13.709810
std        11.531805
min         0.300000
25%         5.000000
50%        10.500000
75%        19.500000
max        74.800000
Name: ESTIMATE, dtype: float64

In [19]:
death_rate['ESTIMATE'].mean()

13.709810357403356

In [20]:
death_rate['ESTIMATE'].median()

10.5

In [21]:
death_rate['ESTIMATE'].std()

11.531805309076454

In [30]:
Q1=death_rate['ESTIMATE'].quantile(.25)
Q3=death_rate['ESTIMATE'].quantile(.75)

IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR

Outlier=death_rate[(death_rate['ESTIMATE']<lower)] | death_rate[(death_rate['ESTIMATE']>upper)]
Outlier

,INDICATOR,UNIT,UNIT_NUM,STUB_NAME,STUB_NAME_NUM,STUB_LABEL,STUB_LABEL_NUM,YEAR,YEAR_NUM,AGE,AGE_NUM,ESTIMATE,FLAG
1904,False,False,False,False,False,False,False,False,False,False,False,False,False
1946,False,False,False,False,False,False,False,False,False,False,False,False,False
1947,False,False,False,False,False,False,False,False,False,False,False,False,False
1955,False,False,False,False,False,False,False,False,False,False,False,False,False
1956,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5425,False,False,False,False,False,False,False,False,False,False,False,False,False
5426,False,False,False,False,False,False,False,False,False,False,False,False,False
6306,False,False,False,False,False,False,False,False,False,False,False,False,False
6342,False,False,False,False,False,False,False,False,False,False,False,False,False
6343,False,False,False,False,False,False,False,False,False,False,False,False,False

In [36]:

death_rate.corr(method='pearson', numeric_only=True)

,UNIT_NUM,STUB_NAME_NUM,STUB_LABEL_NUM,YEAR,YEAR_NUM,AGE_NUM,ESTIMATE
UNIT_NUM,1.000000,0.018732,0.018631,-0.009753,-0.010751,0.535581,0.116223
STUB_NAME_NUM,0.018732,1.000000,0.956913,0.130397,0.145731,0.018175,-0.041625
STUB_LABEL_NUM,0.018631,0.956913,1.000000,0.068506,0.075545,0.023829,-0.069756
YEAR,-0.009753,0.130397,0.068506,1.000000,0.956126,-0.015021,-0.067331
YEAR_NUM,-0.010751,0.145731,0.075545,0.956126,1.000000,-0.016513,-0.063230
AGE_NUM,0.535581,0.018175,0.023829,-0.015021,-0.016513,1.000000,0.325693
ESTIMATE,0.116223,-0.041625,-0.069756,-0.067331,-0.063230,0.325693,1.000000


The strong correlation between STUB_NAME_NUM and STUB_LABEL_NUM suggests that these columns might be representing similar or related categorical data.
The moderate correlation between UNIT_NUM and AGE_NUM could indicate that units are associated with certain age groups.
The strong correlation between YEAR and YEAR_NUM implies these columns are likely representing the same or very similar time-related data.

In [37]:
death_rate.groupby('YEAR')['ESTIMATE'].agg(['mean','sum'])

           mean     sum
YEAR
1950  17.017568  1259.3
1960  16.171233  1180.5
1970  15.542105  1181.2
1980  14.989247  1394.0
1981  14.904938  1207.3
1982  15.116049  1224.4
1983  15.571250  1245.7
1984  15.640741  1266.9
1985  15.042373  1775.0
1986  15.898077  1653.4
1987  15.939423  1657.7
1988  15.221186  1796.1
1989  15.343220  1810.5
1990  15.394915  1816.6
1991  15.195798  1808.3
1992  14.381667  1725.8
1993  14.585124  1764.8
1994  14.553333  1746.4
1995  14.195000  1703.4
1996  13.563115  1654.7
1997  13.430833  1611.7
1998  13.164463  1592.9
1999  11.850327  1813.1
2000  11.706579  1779.4
2001  11.809211  1795.0
2002  11.941447  1815.1
2003  11.606494  1787.4
2004  12.204575  1867.3
2005  11.775484  1825.2
2006  11.886275  1818.6
2007  12.061184  1833.3
2008  12.012102  1885.9
2009  12.233121  1920.6
2010  12.807097  1985.1
2011  12.600637  1978.3
2012  13.290850  2033.5
2013  13.249032  2053.6
2014  13.447134  2111.2
2015  13.925786  2214.2
2016  14.350633  2267.4
2017  14.865409  2363.6
2018  15.290347  3960.2


The strong correlation between STUB_NAME_NUM and STUB_LABEL_NUM suggests that these columns might be representing similar or related categorical data.
The moderate correlation between UNIT_NUM and AGE_NUM could indicate that units are associated with certain age groups.
The strong correlation between YEAR and YEAR_NUM implies these columns are likely representing the same or very similar time-related data.